name: test-ssh
on:
  push:

jobs:
  test-ssh:
    name: test-ssh
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Node installation
        id: install_node
        uses: actions/setup-node@v2-beta
        with:
          node-version: '14.16.1'
          

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_SECRET }} 
          known_hosts: 'just-a-placeholder-so-we-dont-get-errors'          
          
      #
      - name: Run tests_pipeline from sarah-smartmenu-blayn-test
        id: run_tests_pipeline
        run: |  
          git clone git@github.com:sarah30/sarah-smartmenu-blayn-test.git
          cd  sarah-smartmenu-blayn-test
          echo $GITHUB_SHA > deploy.txt
          cat deploy.txt
          git add deploy.txt
          git commit -a -m "Automatic start testing commit $GITHUB_SHA"
          git push
